//Settings Service list api
export const SETTING_SERVICE_PENDING = 'SETTING_SERVICE_PENDING'
export const SETTING_SERVICE_ERROR = 'SETTING_SERVICE_ERROR'
export const SETTING_SERVICE_SUCCESS = 'SETTING_SERVICE_SUCCESS'

//Faq list api
export const FAQ_LIST_PENDING = 'FAQ_LIST_PENDING'
export const FAQ_LIST_ERROR = 'FAQ_LIST_ERROR'
export const FAQ_LIST_SUCCESS = 'FAQ_LIST_SUCCESS'

//Complaint list api
export const COMPLAINT_LIST_PENDING = 'COMPLAINT_LIST_PENDING'
export const COMPLAINT_LIST_ERROR = 'COMPLAINT_LIST_ERROR'
export const COMPLAINT_LIST_SUCCESS = 'COMPLAINT_LIST_SUCCESS'

//Notification list api
export const NOTIFICATION_LIST_PENDING = 'NOTIFICATION_LIST_PENDING'
export const NOTIFICATION_LIST_ERROR = 'NOTIFICATION_LIST_ERROR'
export const NOTIFICATION_LIST_SUCCESS = 'NOTIFICATION_LIST_SUCCESS'

//RIDE list api
export const RIDE_LIST_PENDING = 'RIDE_LIST_PENDING'
export const RIDE_LIST_ERROR = 'RIDE_LIST_ERROR'
export const RIDE_LIST_SUCCESS = 'RIDE_LIST_SUCCESS'


//Referral api
export const REFERRAL_PENDING = 'REFERRAL_PENDING'
export const REFERRAL_ERROR = 'REFERRAL_ERROR'
export const REFERRAL_SUCCESS = 'REFERRAL_SUCCESS'

//Privacy Policy Actions
export const PRIVACY_SERVICE_PENDING = 'PRIVACY_SERVICE_PENDING'
export const PRIVACY_SERVICE_ERROR = 'PRIVACY_SERVICE_ERROR'
export const PRIVACY_SERVICE_SUCCESS = 'PRIVACY_SERVICE_SUCCESS'

//Check Phone
export const CHECK_PHONE_PENDING = 'CHECK_PHONE_PENDING'
export const CHECK_PHONE_ERROR = 'CHECK_PHONE_ERROR'
export const CHECK_PHONE_SUCCESS = 'CHECK_PHONE_SUCCESS'

//Register
export const CREATE_COUNTRY_CODE = 'CREATE_COUNTRY_CODE'
export const CREATE_PHONE_NUMBER = 'CREATE_PHONE_NUMBER'
export const CREATE_PHONE_WITH_CODE = 'CREATE_PHONE_WITH_CODE'
export const CREATE_FIRST_NAME = 'CREATE_FIRST_NAME'
export const CREATE_LAST_NAME = 'CREATE_LAST_NAME'
export const CREATE_EMAIL_ADDRESS = 'CREATE_EMAIL_ADDRESS'
export const CREATE_LOGIN_PASSWORD = 'CREATE_LOGIN_PASSWORD'

export const REGISTER_PENDING = 'REGISTER_PENDING'
export const REGISTER_ERROR = 'REGISTER_ERROR'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'

//Login
export const LOGIN_PENDING = 'LOGIN_PENDING'
export const LOGIN_ERROR = 'LOGIN_ERROR'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'

//Forgot
export const CREATE_FORGOT_PHONE_WITH_CODE = 'CREATE_FORGOT_PHONE_WITH_CODE'

//Profile
export const PROFILE_PENDING = 'PROFILE_PENDING'
export const PROFILE_ERROR = 'PROFILE_ERROR'
export const PROFILE_SUCCESS = 'PROFILE_SUCCESS'
export const UPDATE_PROFILE_PICTURE = 'UPDATE_PROFILE_PICTURE'

//Wallet
export const ADD_WALLET_PENDING = 'ADD_WALLET_PENDING'
export const ADD_WALLET_ERROR = 'ADD_WALLET_ERROR'
export const ADD_WALLET_SUCCESS = 'ADD_WALLET_SUCCESS'

export const WALLET_PENDING = 'WALLET_PENDING'
export const WALLET_ERROR = 'WALLET_ERROR'
export const WALLET_SUCCESS = 'WALLET_SUCCESS'

//Booking
export const PICKUP_ADDRESS = 'PICKUP_ADDRESS'
export const PICKUP_LAT = 'PICKUP_LAT'
export const PICKUP_LNG = 'PICKUP_LNG'
export const DROP_ADDRESS = 'DROP_ADDRESS'
export const DROP_LAT = 'DROP_LAT'
export const DROP_LNG = 'DROP_LNG'
export const KM = 'KM'
export const PROMO = 'PROMO'
export const RESET = 'RESET'
export const ACTIVE_VEHICLE = 'ACTIVE_VEHICLE'
export const ACTIVE_VEHICLE_DETAILS = 'ACTIVE_VEHICLE_DETAILS'
export const PACKAGE_ID = 'PACKAGE_ID'